# Generated by Django 5.1 on 2025-08-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medlexicon', '0003_remove_word_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name']},
        ),
        migrations.AlterModelOptions(
            name='wordformat',
            options={'ordering': ['format_name']},
        ),
    ]
